services:
  postgres:
    container_name: POSTGRES
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"

  rabbitmq:
    container_name: RABBITMQ
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  discovery-service:
    container_name: DISCOVERY-SERVICE
    build: ./discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    container_name: API-GATEWAY
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service

  customer-service:
    container_name: CUSTOMER-SERVICE
    build: ./customer-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
      - discovery-service

  delivery-service:
    container_name: DELIVERY-SERVICE
    build: ./delivery-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
      - discovery-service

  order-service:
    container_name: ORDER-SERVICE
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
      - discovery-service

  restaurant-service:
    container_name: RESTAURANT-SERVICE
    build: ./restaurant-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - rabbitmq
      - discovery-service

volumes:
  postgres-data:
